### PR TITLE
Add support for Keyboard Input

### PR DESCRIPTION
**Pull request by digumx**
### Adds support for keyboard input.

Input model is state poll on requirement. Support for callback based models alongside this model may be
added in the future.

Keyboard input is obtained by simply querying weather a particular key is being pressed or not. This is done by calling something like `renderer.getKeyboard().isKeyPressed(RetiKey::SOME_KEY)`. This function returns a bool which is set to true if the key was pressed at the time of call, else set to false. The argument passed is of the type `RetiKey`, which is an enum containing all named keys supported by Reticle. For a full list of the 118 keys supported, see [RetiKeyboard.h](https://github.com/digumx/ProjectReticle/blob/Add-Keyboard-Input/Reticle/Headers/RetiKeyboard.h).

### Note:

 -  Keys in RetiKey are named according to the US Keyboard Layout. For other keyboard layouts, the keys will still work, but it may be more meaningful to use other names.
 -  Currently, input from platform specific keys that are not part of the keyboard layout, keys like volume and brightness controls, play/pause, etc., cannot be listened for. Since these keys are completely platform dependent, support for them cannot be added in a platform agnostic manner.
 -  Note that under the current model, if a key press and release is done between two calls to `isKeyPressed()`, the key will not be registered. This may be solved by adding support for sticky keys in the future.
 -  Also note that it is recommended to call `RetiKeyboard::addKeyListener(RetiKey)` before polling key states for every key whose state shall be polled. Not doing so results in a slight performance penalty whenever `isKeyPressed(RetiKey)` is called for a key that was not being listened to previously. It also makes this first call to `isKeyPressed(RetiKey)` always return false, thereby missing a possible keystroke.
 -  The input system is completely thread safe.
 -  Currently, the input system will produce incorrect behavior if multiple instances of `RetiRenderer` are active and listening.
 -  Also note that keystrokes are registered by the `RetiKeyboard` attached to a `RetiRenderer` only while the `RetiRendere` is rendering. Pausing the renderer may pause key registering.

### Some other unrelated notes:

The following changes were first noticed and added to this branch, but are completely unrelated to keyboard input and must be pushed to all other branches as soon as possible. This will probably be done through a separate PR.

 -  Fixed copy assignment operator of `RetiRenderer` to match code-style better, and to be more safer.
 -  Added member function `RetiCamera& RetiRenderer::getCamera()` to `RetiRenderer` so that Reticle users are able to access the camera being used by a `RetiRenderer` to render. This makes things like transforming the camera much easier.

### CODE REVIEW

**Comment by digumx** [comment]
@technosap  Test the above PR too. Again, you can use [ReticleLinuxTest](https://github.com/digumx/ReticleLinuxTest)'s Add-Keyboard-Input branch to test stuff. Also, just read through the notes and see if some of the possible future features are immediately required.

@Ani-98 Check the `RetiKey` enum in [RetiKeyboard.h](https://github.com/digumx/ProjectReticle/blob/Add-Keyboard-Input/Reticle/Headers/RetiKeyboard.h) to see if I am missing some important key. Note, i'm not considering platform specific keys.

**Comment by digumx** [comment]
Also, deadline for this is 4 days, that is 19th July.

**Comment by technosap** [comment]
There are existing conflicts in this pull request due to merging of Assimp-Update Branch, please fix issues before we can merge

**Comment by digumx** [comment]
I've reverted [PR#4](https://github.com/CodeCancer/ProjectReticle/pull/4) to merge this PR first. Merging now.

**Pull request merged**
