### PR TITLE
Add Assimp based Asset Import support - Reticle v0.0.7a

### PR DESCRIPTION
**Pull request by digumx**
Wrote, and tested code to add complete asset import support to Reticle v0.0.7a. 

To use: 

 -  Create a `RetiSceneObject` with the `RetiSceneObject(const std::string&)` constructor. Use a platform specific file path to the asset to be imported. Absolute paths can save a lot of trouble.

 -  Add it to the `RetiRenderer` with `RetiRenderer::addSceneObject(RetiSceneObject*)`.

 -  Render as usual.

@technosap Please review and test this PR, you can clone from digumx/ProjectReticle/Assimp-Update-v0.0.7a and test it. Test this thoroughly with a large number of files. I will merge this myself on July 20, if no issues or comments are made.

### CODE REVIEW

**Comment by digumx** [comment]
@technosap U could use this to help you with the testing and review: [ReticleWindowsTest](https://github.com/digumx/ReticleWindowsTest).

**Comment by digumx** [comment]
@digumx @technosap @Ani-98 Note that whoever merges this branch to master, follow the merge with a direct commit to change the string literal at line 30 of [RetiRenderer.h](https://github.com/CodeCancer/ProjectReticle/blob/master/Reticle/Headers/RetiRenderer.h) to `"0.0.8a"`. Don't include the `-linux` or `-windows` like I used to do earlier.

Note, this change is not committed into this PR because I am also working on another feature (will PR soon), and I'm not sure which of these PRs will be merged into master first.

**Comment by technosap** [comment]
Ok, @digumx  i havent gotten time to actually build and get it running, ill do that as soon as i have dualbooted my device, instruct me then. meanwhile merge it

**Comment by digumx** [comment]
It's ok, @technosap, in that case I'll do some testing and merge it myself, but not before 18th just in case u get time to do some tests of ur own. It's better to have a hanging branch than a shaky master.

**Comment by digumx** [comment]
And the last set of commits fixes (again, hopefully), [Issue6](https://github.com/CodeCancer/ProjectReticle/issues/6) for the Assimp-Update-v0.0.7a branch. The changes are identical to those described in [PullRequest7](https://github.com/CodeCancer/ProjectReticle/pull/7), just replace `RetiMesh` with `RetiSceneObject`. 

@technosap , please review and comment if you find this does solve the issue. If so, close [Issue6](https://github.com/CodeCancer/ProjectReticle/issues/6).

**Pull request merged**
